### ISSUE TITLE
PyInstaller and Wexpect

### ISSUE THREAD

**Issue by AmandaBeuno** [raczben/wexpect#12] opened 2019-10-04 07:32 UTC
**Describe the bug**
The problem I am facing is that whenever I convert my app using PyInstaller to an EXE. I get the following error.
```
Traceback (most recent call last):
     File "site-packages\wexpect.py", line 307, in spawn
     File "site-packages\wexpect.py", line 1648, in __init__
     File "site-packages\wexpect.py", line 480, in __init__
     File "site-packages\wexpect.py", line 1709, in _spawn
     File "site-packages\wexpect.py", line 1939, in spawn
     File "site-packages\wexpect.py", line 2028, in startChild
pywintypes.error (2, 'CreateProcess', "The system cannot find the file specified.')
```

**To Reproduce**

1- Create a new script.
2- Import wexpect.
3- Spawn cmd or any application in that script.
4- from the command line run "pyinstaller scriptname.py" to convert it to exe.
5- Finally, run the executable.

**Expected behavior**
Spawn should run without errors.

**Screenshots**

**Environment:**
 - [windows version] Windows 10
 - [Python version] 3.7.4
 - [wexpect version] 2.3.6
 - [pyinstaller version] 4.0.dev

**Additional context**
I understand that the problem here is with the variable 'commandLine'. I noticed in the code that it already check for py2exe frozen attribute.

All the best,
A

**Comment by raczben** [comment] 2019-10-07 08:28
There are couple of other open issues, which causes instant crash, so this issue will fixed later. Sorry for this decision.

**Comment by cryerenable** [comment] 2019-11-21 13:30
Same error(

I hope they will fix it soon, I can’t build a project without wexpect (

[windows version] Windows 10 [Version 10.0.18362.476]
[Python version] v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05
[wexpect version] 2.3.9
[pyinstaller version] 3.5
![9RgTfNldAF](https://user-images.githubusercontent.com/15123106/69342280-e3bfed80-0c73-11ea-8f3e-d00d92aea612.png)

**Comment by RyanLiuF** [comment] 2020-02-14 05:59
Same error in PyInstaller.
I hope this error will fix it soon.
[windows version] Windows 10
[Python version] v3.7.4 64-bit
[wexpect version] 3.2.0
[pyinstaller version] 3.5

**Comment by raczben** [comment] 2020-02-19 22:01
Hi all,

Sorry for the late reply, but I am the only maintainer...

The root problem is that pyinstaller has no explicit python executable. While wexpect call it, when it creates child.
It seems a bit complicated issue, it will took 1-2 weeks to solve.

**Comment by cryerenable** [comment] 2020-02-19 22:33
Yeah..im waiting for solve,thx u😗

**Comment by raczben** [comment] 2020-02-23 18:23
Hi All,

**Pyinstaller support is now beta!**

You should use the new-structured wexpect, by setting `WEXPECT_SPAWN_CLASS` environment variable to `SpawnPipe`, and you should create wexpect executable manually, but it works!

Read [this wiki page][1], for more information.

((The stable release, will come along with the new-structured wexpect aprox. a month later.))

[1]: https://github.com/raczben/wexpect/wiki/Wexpect-with-pyinstaller

**Comment by RyanLiuF** [comment] 2020-03-12 01:34
Pretty cool, tks!!

**Comment by dgburr** [comment] 2020-03-28 03:54
Great work, @raczben!  I am using wexpect in a project and I was able to create a packaged .exe file based upon the instructions you provided.  However I would like to make a couple of suggestions:

1. The instructions on the wiki say to use `os.environ['WEXPECT_SPAWN_CLASS']=SpawnPipe` whereas it should say `os.environ['WEXPECT_SPAWN_CLASS']='SpawnPipe'`
2. The current implementation is difficult to use if pyinstaller is run with the `--onefile` option.  I was able to make it work as follows:

a) Add the following code before and after calls to `wexpect.spawn()`:

```
real_executable = sys.executable
try:
    if sys._MEIPASS is not None:
        sys.executable = os.path.join(sys._MEIPASS, "wexpect", "wexpect.exe")
except AttributeError:
    pass
p = wexpect.spawn(cmd)
sys.executable = real_executable
```
b) Run pyinstaller with the following command:

`pyinstaller --onefile --add-data <path_to_wexpect>\dist;. myscript.py`

However it would be much nicer if you could add an environment variable (e.g. `WEXPECT_EXECUTABLE`) which can be used to point to a custom location of wexpect.exe, instead of the current implementation which hard-codes the path as `sys.executable + "\..\wexpect\wexpect.exe"`

**Comment by ZionP92** [comment] 2020-04-13 13:04
@raczben I have the same problem, and I did it just as <https://github.com/raczben/wexpect/wiki/Wexpect-with-pyinstaller> says, but in my case it brings another GUI not spawning a script that I put. I'm using pyqt5 for main.py and spawn child.py which has excel handling functions with an input line. I already asked it on stackflow website as well, and it's a bit long to say so I'm leaving the url here <https://stackoverflow.com/questions/61172294/failed-using-pyinstaller-to-make-an-exe-from-two-python-scripts-which-connect-th>, I'm sorry if you are busy but if you don't mine I hope you can tell me if it's the wexpect collides with pyinstaller. my codes are working fine on python

**Comment by raczben** [comment] 2020-04-13 18:25
Hi,

Please answer all of these points:
 1. Can you use pyinstaller in simple cases _successfully_?
 2. Please describe your environment. (Wexpect version, Windows version, Python version, etc)
 3. Please turn on logging. Set `WEXPECT_LOGGER_LEVEL` environment variable to `INFO`. It will create one log-file for the host and another for the child. Please send me the logs of correct and faulty behavior. (Note, that logs can contain sensitive information. In this case, remove those lines.)
 4. Can you send a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)? Please reduce your code to as minimal as it is possible, but with the same error. It will speed up the fix.

**Comment by cnaferdie** [comment] 2020-04-24 21:44
Hi @raczben, can you please provide an example of the following. 

" You should use the new-structured wexpect, by setting WEXPECT_SPAWN_CLASS environment variable to SpawnPipe, and you should create wexpect executable manually, but it works! "

Sorry I'm new to python and below line from my script is not working after I used pyinstaller to convert .py to .exe. Hope to hear from you soon. 
child = wexpect.SpawnPipe('ssh "-o StrictHostKeyChecking=no" ' + ap);

**Comment by raczben** [comment] 2020-04-26 06:43
Hi @cnaferdie ,

Please read [this wiki page][1] thoroughly.

If you still have a problem please answer all of these points:
 1. Can you use pyinstaller in simple cases _successfully_? (I mean bundling my [hello-wexpect](https://github.com/raczben/wexpect/blob/master/examples/hello_wexpect.py) example script.)
 2. Please describe your environment. (Wexpect version, Windows version, Python version, etc)
 3. Please turn on logging. Set `WEXPECT_LOGGER_LEVEL` environment variable to `INFO`. It will create one log-file for the host and another for the child. Please send me the logs of correct and faulty behavior. (Note, that logs can contain sensitive information. In this case, remove those lines.)
 4. Can you send a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)? Please reduce your code to as minimal as it is possible, but with the same error. It will speed up the fix.

[1]: https://github.com/raczben/wexpect/wiki/Wexpect-with-pyinstaller

**Comment by cnaferdie** [comment] 2020-04-26 09:57
Hi @raczben,
I read the wiki again and followed the structure below and it works! So it looks like the users have to install wexpect.exe also on their computers for this work, correct?

dist
 ├─wexpect
 │  ├─ ...
 │  ├─ wexpect.exe
 │  └─ ...
 └─your_script
    ├─ ...
    ├─ your_script.exe
    └─ ...

**Comment by raczben** [comment] 2020-04-26 20:04
Hi @cnaferdie 

I'm glad to hear that it's working.
Installing Python isn't needed. (It would make no sense...)
You should deliver only the two bundles: the script of yours and the wexpect.

**Comment by cnaferdie** [comment] 2020-04-26 21:58
> Hi @cnaferdie 
> 
> I'm glad to hear that it's working.
> Installing Python isn't needed. (It would make no sense...)
> You should deliver only the two bundles: the script of yours and the wexpect.
> 

Okay. So I guess it's not yet possible to use the --onefile of the pyinstaller for now. I hope this will possible in the future.

 Thank you so much for your help. Really appreciate it. :)

**Comment by raczben** [comment] 2020-04-27 06:09
No, wexpect does not support onefile mode right now. Please read [this ](https://github.com/raczben/wexpect/issues/12#issuecomment-605390122)for a workaround.

**Comment by cnaferdie** [comment] 2020-04-27 08:33
> > Hi @cnaferdie 
> > 
> > I'm glad to hear that it's working.
> > Installing Python isn't needed. (It would make no sense...)
> > You should deliver only the two bundles: the script of yours and the wexpect.
> > 
> 
> Okay. So I guess it's not yet possible to use the --onefile of the pyinstaller for now. I hope this will be possible in the future.
> 
>  Thank you so much for your help. Really appreciate it. :)


I just tried distributing the folders to one of my collegues. It's not woring on her PC.

**Comment by cnaferdie** [comment] 2020-04-27 16:12
> No, wexpect does not support onefile mode right now. Please read [this ](https://github.com/raczben/wexpect/issues/12#issuecomment-605390122)for a workaround.


I have this in my script:

                real_executable = sys.executable
                try:
                    if sys._MEIPASS is not None:
                        sys.executable = os.path.join(sys._MEIPASS, "wexpect", "wexpect.exe")
                except AttributeError:
                    pass
                child = wexpect.spawn('ssh -o "StrictHostKeyChecking=no" ' + ap)


But I'm having this error message:

ExceptionPexpect: Wexpect executable: >>C:\Users\FORMAN~1\AppData\Local\Temp\_MEI137202\wexpect\..\wexpect\wexpect.exe<< not found.
It's not working either. Check device manually

**Comment by Starstorm** [comment] 2020-07-01 18:33
Hi all,

So I'm having an issue with this, it's probably quite easy to fix but I can't seem to get it to work. So I followed the wiki instructions and ensured both my script folder and the wexpect I compiled are in the same directory (I'm using Windows 10). Then I attempt to run a minimalist main.py script:

import wexpect, os
os.environ['WEXPECT_LOGGER_LEVEL']='INFO'
cmd_string = r"C:\Windows\System32\cmd.exe"
child = wexpect.spawn(cmd_string)

This works fine when I just do python main.py, but it does not run after using PyInstaller and then running the exe. The error it gives me when executing the .exe is the following:

Traceback (most recent call last):
  File "cli.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\pykerasenv\gocheater\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "main.py", line 4, in <module>
  File "site-packages\wexpect-4.0.1.dev4-py3.7.egg\wexpect\host.py", line 878, in __init__
  File "site-packages\wexpect-4.0.1.dev4-py3.7.egg\wexpect\host.py", line 247, in __init__
  File "site-packages\wexpect-4.0.1.dev4-py3.7.egg\wexpect\host.py", line 897, in connect_to_child
wexpect.wexpect_util.TIMEOUT: Connect to child has been timed out.
[10188] Failed to execute script cli

Any ideas whats causing this?

Thanks!

**Comment by Starstorm** [comment] 2020-07-03 17:27
UPDATE:
Solved the problem! The issue was that I compiled the wexpect executable under setuptools 45.0.0 and I didn't have 'pkg_resources.py2_warn' added as a hiddenimport - thus it would successfully find wexpect, attempt to load it, and it would instantly crash.

Yeesh...

**Comment by raczben** [comment] 2021-02-01 08:56
Closing this topic...

If you have a problem using pyinstaller please read [this wiki page](https://github.com/raczben/wexpect/wiki/Wexpect-with-pyinstaller), for more information.

**Closed by raczben** 2021-02-01 08:56 UTC
Labels: bug

**Comment by eirisdg** [comment] 2021-02-07 01:55
Hi @raczben 

I've followed the wiki, but i cannot do ir work.

When I call wexpect.spawn I get error.
'wexpect' has no attribute 'spawn'

The structure is the same than in the wiki.

My script is very simple, but still doesn't work:
```python
import wexpect

prompt = '[A-Za-z]\:.+>'
child = wexpect.spawn('cmd.exe')
child.expect(prompt)
```

**Comment by freQniK** [comment] 2023-01-17 02:29
Hai - Do you have a Bitcoin or Monero address I can send some funds to as a donation for a wonderful project that saved my rear end when porting a Linux & OS X app that relied heavily on pexpect but ran into issues on Windows with. It turns out, the Pyinstaller work-a-round was a success and I'd like to show my appreciate by sending some neros or satoshis your way. 

Thanks you very much for a wonderful wrapper library!
